### ISSUE TITLE
break apart uber module

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem-deploy#15]
now that we've been using puppet for a while and know better things about how to run it, we probably need to restructure the uber module into a few different components.

probably delete the uber module and make modules or classes that look like this:

sideboard
sideboard_plugin
postgres+replication (so we can decouple the DB from the web/proxy stuff)
nginx

it may be worth investigating using custom facter facts to define stuff like master/slave DB ips, so that we can just type stuff like %%master_db_ip%% and %%slave_db_ip%%

we should also create a new class in the 'site' module called 'ubersystem_ez_install' and when it is included, it magically does the right thing, installing sideboard+uber plugins+nginx+db and all other config stuff on a node.

if people want to get fancy, they can just not include the EZ install module to include various parts of sideboard/db/proxy and do it in more broken out steps, allowing stuff like having the db, proxy, and sideboard running on different servers.

**Comment by binary1230** [comment]
btw we broke up the module so closing this.

**Comment by EliAndrewC** [comment]
There's one module left to extract which I plan on doing this weekend, which is to pull out the Tabletop code into a separate ``tabletop`` plugin.  I think it's okay to close this ticket now though.
